### ISSUE TITLE
我使用了 下面这个方法 报401

### ISSUE THREAD

**Issue by devops-fj** [cloudbase/go-winrm#4]
package main

// We use a forked version of net/http and crypto/tls
// because the standard libs do now support renegotiation

import (
    "fmt"
    "launchpad.net/gwacl/fork/http"
    "github.com/trobert2/winrm"
)

func main(){
    p := winrm.ShellParams{}
    Soap := winrm.SoapRequest{
        Endpoint:"https://192.168.100.154:5986/wsman",
        Username:"Administrator",
        Passwd:"Passw0rd",
        AuthType:"BasicAuth",
        HttpInsecure:true,
        HttpClient: &http.Client{},
    }
    cmdParam := winrm.CmdParams{
        Cmd: "dir",
        Args: "c:\\ /A",
    }

    v := &winrm.Envelope{}
    strdout, stderr, ret_code, _ := v.RunCommand(p, cmdParam, Soap)
    fmt.Printf("Output:%s\nError: %s\nCode:%v\n", strdout, stderr, ret_code)
}

**Comment by gabriel-samfira** [comment]
Hi!

This repo is unmaintained and will probably fail in many ways. I encourage you to use: https://github.com/masterzen/winrm

Which should have support for renegotiation.

**Comment by devops-fj** [comment]
ok! 谢谢&nbsp;


榛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月18日(星期二) 晚上8:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloudbase/go-winrm] 我使用了 下面这个方法 报401 (Issue #4)





 
Hi!
 
This repo is unmaintained and will probably fail in many ways. I encourage you to use: https://github.com/masterzen/winrm
 
Which should have support for renegotiation.
